export const GETTING_INVOICE_LIST = 'GETTING_INVOICE_LIST';

export const GOT_INVOICE_LIST = 'GOT_INVOICE_LIST';

export const UPDATE_ACTIVE_INVOICE = 'UPDATE_ACTIVE_INVOICE';

export const CLEAR_ACTIVE_INVOICE = 'CLEAR_ACTIVE_INVOICE';

export const SAVE_INVOICE = 'SAVE_INVOICE';

export const LOAD_INVOICE = 'LOAD_INVOICE';
